# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI
on:
  push:
    branches:
      - master
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          gradle-version: 7.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: bungeecord
          path: bungeecord/build/libs
      - uses: actions/upload-artifact@v2
        with:
          name: velocity
          path: velocity/build/libs
      - uses: softprops/action-gh-release@v1
        name: Release
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            bungeecord/build/libs/bungeecord-all.jar
            velocity/build/libs/velocity-all.jar